// "": "",
export default {
    "en": {
        "projectName": "Yucca",
        "firstUseWelcome": "Welcome to Yucca",
        "firstUseContent": `<strong>Press CTRL+D at any time to display the help page.</strong> <br /> Since this is the first time you're using this application, please setup the next default values to be used by the application. <br/> <br/> All the settings can be
		<strong>modified </strong> at any time.`,
        "firstUseSetupFolder": "Setup the default folder to store your projects.",
        "firstUseSetupColor": "Setup the default application color",
        "aboutContent": "Yucca is a simple project manager built with Vue and Electron",
        "searchLabel": "Search by tags, title, project ...",
        "helperTitle": "Helper/Shortcuts",
        "newMilestoneLabel": "Milestone Name",
        "category": "Category",
        "milestone": "Milestone",
        "noTagFound": "No tag found. Tags needs to be created before being used.",
        "export": "Export",
        "general": "General",
        "about": "About",
        "edit": "Edit",
        "save": "Save",
        "cancel": "Cancel",
        "browse": "Browse",
        "done": "Done",
        "close": "Close",
    },
    "fa": {
        "projectName": "یوکا",
        "firstUseWelcome": "به یوکا خوش آمدید",
        "firstUseContent": `<strong>Press CTRL+D at any time to display the help page.</strong> <br /> Since this is the first time you're using this application, please setup the next default values to be used by the application. <br/> <br/> All the settings can be
		<strong>modified </strong> at any time.`,
        "firstUseSetupFolder": "Setup the default folder to store your projects.",
        "firstUseSetupColor": "Setup the default application color",
        "aboutContent": "یوکا برنامه جهت مدیریت پروژه ها می باشد که با Vue و Electron ساخته شده است.",
        "searchLabel": "جستجو با عنوان ، تگ ، پروژه و ...",
        "helperTitle": "Helper/Shortcuts",
        "newMilestoneLabel": "Milestone Name",
        "category": "دسته بندی",
        "milestone": "Milestone",
        "noTagFound": "تگی پیدا نشد. ابتدا باید تگ تعریف کنید.",
        "export": "خروجی",
        "general": "عمومی",
        "about": "درباره",
        "edit": "ویرایش",
        "save": "ذخیره",
        "cancel": "لغو",
        "browse": "Browse",
        "done": "تایید",
        "close": "بستن",
    }
}